#! /bin/bash


##Killall

##########################################################################################################################
# Kill allprocesses quietly and wait till they have been shut down before we start them again in the "Autostart" section #
##########################################################################################################################

killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done

#killall -q nitrogen
#while pgrep -u $UID -x nitrogen >/dev/null; do sleep 1; done
##Killall end

##Autostart

###sxhkd
sxhkd &
###sxhkd end

###picom
picom &
###picom end


###Turn numlock on
numlockx on &
###Turn numlock on end


###bspwm swallow script

pgrep ~/.config/desktopsetup/gitstuff/bspswallow/bspswallow || ~/.config/desktopsetup/gitstuff/bspswallow/bspswallow &

###bspwm swallow script end

##Autostart end

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 0

bspc rule -a Emacs state = tiled

$HOME/.config/desktopsetup/polybar/singlepolybar.sh

mcounter=0
for m in $(polybar --list-monitors | cut -d":" -f1); do
	((mcounter=mcounter+1))
done

if [ $mcounter -gt 0 ]; then
	if [ $mcounter -eq 1 ]; then
		echo "kleiner 1 = 1"
		bspc monitor $(polybar --list-monitors | cut -d":" -f1) -d 1 2 3 4
#		$HOME/.config/desktopsetup/polybar/launchsinglepolybar.sh
	else
		#echo "greater 1 mcounter=" $mcounter 
		#echo "start"
		#i=1
		#for z  in $listOfMonitors; do
		#	bspc monitor -d Desktop
		#done
		anzDesktopsPerMonitor=3
		listOfMonitors=$(polybar --list-monitors | cut -d":" -f1)
		#while (( i < (( mcounter*anzDesktopsPerMonitor )))); do
        	#	echo $i
        	#	for k in $listOfMonitors; do
                #		echo $k " and " $i
                #		bspc monitor $k -a $i
                #		((i=i+1))
        	#	done    
		#done

		k=1
		for m in $(polybar --list-monitors | cut -d":" -f1); do
			bspc monitor $m -d $k $((k=k+2)) $((k=k+2))
			k=2
		done
		#polybar bar &
		#$HOME/.config/desktopsetup/polybar/launchtwopolybars.sh
		###Polybar end
	fi
fi
