#! /bin/sh


##Killall

##########################################################################################################################
# Kill allprocesses quietly and wait till they have been shut down before we start them again in the "Autostart" section #
##########################################################################################################################

killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done

#killall -q nitrogen
#while pgrep -u $UID -x nitrogen >/dev/null; do sleep 1; done
##Killall end

##Autostart

###sxhkd
sxhkd &
###sxhkd end

###Set wallpaper
#nitrogen --restore &
###Set wallpaper end

###Polybar
#polybar mainbar &

##polybar bar &
$HOME/.config/desktopsetup/polybar/launchpolybar.sh
###Polybar end

##Autostart end

#bspc monitor -d I II III IV V VI VII VIII IX X
##bspc monitor -d 1 2 3
##bspc monitor eDP1 -d I II III IV
##bspc monitor eDP1 -d 1 2 3

bspc monitor -d DVI-D-0 1 2 3
bspc monitor -d HDMI-A-0 4 5 6


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

